language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - composer install --dev
  - composer require phing/phing:2.14.0
before_script:
  - cd tests
script:
  - phpunit